In [47]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [48]:
diabetes_df=pd.read_csv('datasets/diabetes.csv')

In [49]:
diabetes_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72.0,35,169.5,33.6,0.627,50,1
1,1,85,66.0,29,102.5,26.6,0.351,31,0
2,8,183,64.0,32,169.5,23.3,0.672,32,1
3,1,89,66.0,23,94.0,28.1,0.167,21,0
4,0,137,40.0,35,168.0,43.1,2.288,33,1

In [50]:
diabetes_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    float64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    float64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(4), int64(5)
memory usage: 54.1 KB

In [51]:
diabetes_df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,121.677083,72.389323,29.089844,141.753906,32.434635,0.471876,33.240885,0.348958
std,3.369578,30.464161,12.106039,8.890820,89.100847,6.880498,0.331329,11.760232,0.476951
min,0.000000,44.000000,24.000000,7.000000,14.000000,18.200000,0.078000,21.000000,0.000000
25%,1.000000,99.750000,64.000000,25.000000,102.500000,27.500000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,28.000000,102.500000,32.050000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,169.500000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [ ]:
diabetes_df.isnull().sum()

In [ ]:
columns = [
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI"
]

diabetes_df[columns] = diabetes_df[columns].replace(0, np.nan)

In [ ]:
diabetes_df.isnull().sum()

In [ ]:
(diabetes_df == 0).sum()

In [ ]:
diabetes_df.dtypes

In [ ]:
from sklearn.preprocessing import StandardScaler
import pandas as pd

X = diabetes_df.drop("Outcome", axis=1)
y = diabetes_df["Outcome"]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

processed_df = pd.DataFrame(X_scaled, columns=X.columns)
processed_df["Outcome"] = y

In [ ]:
processed_df.to_csv("datasets/processed_dataset.csv", index=False)

In [ ]:
heart_df = pd.read_csv("datasets/heart.csv")
heart_df.head()

In [ ]:
heart_df.info()

In [ ]:
heart_df.describe()

In [ ]:
heart_df.isnull().sum()

In [ ]:
heart_df.dtypes

In [ ]:
from sklearn.preprocessing import StandardScaler

X = heart_df.drop("target", axis=1)
y = heart_df["target"]

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

processed_heart = pd.DataFrame(X_scaled, columns=X.columns)

processed_heart["target"] = y

In [ ]:
processed_heart.to_csv("datasets/processed_heart.csv", index=False)

In [ ]:
kidney_df = pd.read_csv("datasets/kidney_disease.csv")

In [ ]:
kidney_df.head()

In [ ]:
kidney_df.info()

In [ ]:
kidney_df.isnull().sum()

In [ ]:
kidney_df.replace("?", np.nan, inplace=True)

In [ ]:
kidney_df.dtypes

In [ ]:
numeric_columns = [
    "id", "age", "bp", "sg", "al", "su",
    "bgr", "bu", "sc", "sod", "pot", "hemo",
    "pcv", "wc", "rc"
]

for col in numeric_columns:
    kidney_df[col] = pd.to_numeric(kidney_df[col], errors="coerce")

In [ ]:
for col in numeric_columns:
    kidney_df[col] = kidney_df[col].fillna(kidney_df[col].median())

In [ ]:
categorical_columns = [
    "rbc", "pc", "pcc", "ba",
    "htn", "dm", "cad",
    "appet", "pe", "ane",
    "classification"
]

for col in categorical_columns:
    kidney_df[col] = kidney_df[col].fillna(kidney_df[col].mode()[0])

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

for col in categorical_columns:
    kidney_df[col] = encoder.fit_transform(kidney_df[col].astype(str))

In [ ]:
kidney_df.isnull().sum()

In [ ]:
from sklearn.preprocessing import StandardScaler

X = kidney_df.drop("classification", axis=1)
y = kidney_df["classification"]

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

processed_kidney = pd.DataFrame(X_scaled, columns=X.columns)
processed_kidney["classification"] = y

In [ ]:
processed_kidney.to_csv("datasets/processed_kidney.csv", index=False)